//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementySite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int VisitId { get; set; }
        public int PatientId { get; set; }
        public string StaffId { get; set; }
        public string VisitReason { get; set; }
        public Nullable<System.DateTime> VisitStartDate { get; set; }
        public Nullable<System.DateTime> VisitEndDate { get; set; }
        public string PatientStatus { get; set; }
    }
}
