//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementySite
{
    using System;
    using System.Collections.Generic;
    
    public partial class VitalSign
    {
        public int VitalId { get; set; }
        public int VisitId { get; set; }
        public Nullable<int> HeartRate { get; set; }
        public string BloodPressure { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<System.DateTime> TimeTaken { get; set; }
    }
}
